import type { Metadata } from "next";
import { Montserrat, Unbounded } from "next/font/google";
import "./styles/globals.css";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin", "cyrillic"]
});

const unbounded = Unbounded({
    variable: "--font-unbounded",
    subsets: ["latin", "cyrillic"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
