import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Unbounded } from "next/font/google";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin", "cyrillic"]
});


const unbounded = Unbounded({
    variable: "--font-unbounded",
    subsets: ["latin", "cyrillic"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
